# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import productapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('logo', models.ImageField(blank=True, upload_to=productapp.models.get_brandimage_path)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('price', models.IntegerField()),
                ('urladdress', models.URLField()),
                ('content', models.TextField()),
                ('productimg', models.ImageField(blank=True, upload_to=productapp.models.get_productimage_path)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.Brand')),
            ],
        ),
    ]
