# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='url',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='brand',
            name='urladdress',
            field=models.URLField(blank=True),
        ),
    ]
